apiVersion: v1
kind: Service
metadata:
  name: producer
spec:
  ports:
    - port: 14000
      protocol: TCP
      targetPort: 14000
  type: NodePort
  selector:
    app: producer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: producer
    spec:
      # 此处需要
      #kubectl create secret docker-registry registry-pull-secret --namespace=default \
      #--docker-server=192.168.100.249 --docker-username=admin \
      #--docker-password=Harbor12345 --docker-email=xcp.email@gmail.com
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - name: producer
          image: 192.168.100.249/k8s/producer:latest
          env:
            - name: AUTHOR
              value: producer
          ports:
            - containerPort: 14000