apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  ports:
    - port: 15000
      protocol: TCP
      targetPort: 15000
  type: NodePort
  selector:
    app: consumer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      # 此处需要
      #kubectl create secret docker-registry registry-pull-secret --namespace=default \
      #--docker-server=192.168.100.249 --docker-username=admin \
      #--docker-password=Harbor12345 --docker-email=xcp.email@gmail.com
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - name: producer
          image: 192.168.100.249/k8s/consumer:latest
          env:
            - name: AUTHOR
              value: consumer
          ports:
            - containerPort: 15000