apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: 192.168.100.249/study/eureka:1.0
        env:
        - name: AUTHOR
          value: eureka
        ports:
        - containerPort: 7000