apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: 192.168.100.249/dnvip/config:1.0
        env:
        - name: AUTHOR
          value: config-server
        ports:
        - containerPort: 12000