apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  ports:
  - port: 12000
    protocol: TCP
    targetPort: 12000
  type: NodePort
  selector:
    app: config-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: config-server
    spec:
      # 此处需要
      #kubectl create secret docker-registry registry-pull-secret --namespace=default \
      #--docker-server=192.168.100.249 --docker-username=admin \
      #--docker-password=Harbor12345 --docker-email=xcp.email@gmail.com
      imagePullSecrets:
        - name: registry-pull-secret
      containers:
        - name: config-server
          image: 192.168.100.249/k8s/config:latest
          env:
            - name: AUTHOR
              value: config-server
          ports:
            - containerPort: 12000